plugins:

  tools:
    executor: central_deployment_agent
    source: https://github.com/cloudify-incubator/cloudify-proxy-plugin/archive/v1.0.0c.zip

data_types:

  cloudify.datatypes.Deployment:
    properties:
      deployment_id:
        description: >
          This is the deployment that the node is a proxy to.
        required: true
      blueprint_id:
        description: >
          This is the blueprint_id that the deployment is created from.
        required: false
      cloudify_agent_name:
        description: >
          If this is a compute node the name of the cloudify agent.
        required: false
      outputs:
        description: >
          A dictionary of "{ key: value, key: value }".
          Get "key" the deployment.
          Set "value" runtime property to the value of the output.
        required: false
      unvalidated:
        default: {}

node_types:

  cloudify.nodes.DeploymentProxy:
    derived_from: cloudify.nodes.Root
    properties:
      use_external_resource:
        type: boolean
        default: true
      resource_config:
        type: cloudify.datatypes.Deployment
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: tools.cloudify_deployment_proxy.tasks.wait_for_deployment_ready
          inputs:
            state:
              default: 'terminated'
            timeout:
              default: 60
        start:
          implementation: tools.cloudify_deployment_proxy.tasks.query_deployment_data
          inputs:
            daemonize:
              default: false
            interval:
              default: 1
            timeout:
              default: 15

  cloudify.nodes.DeploymentProxy.Compute:
    derived_from: cloudify.nodes.Compute
    properties:
      agent_config:
        default:
          install_method: provided
      use_external_resource:
        type: boolean
        default: true
      resource_config:
        type: cloudify.datatypes.Deployment
        default: {}
    interfaces:
      cloudify.interfaces.cloudify_agent:
        configure:
          implementation: agent.cloudify_agent.installer.operations.configure
          executor: central_deployment_agent
          inputs:
            cloudify_agent:
              remote_execution: false
              name: { get_property: [ SELF, resource_config, cloudify_agent_name ] }
        start:
          implementation: agent.cloudify_agent.installer.operations.start
          executor: central_deployment_agent
          inputs:
            cloudify_agent:
              remote_execution: false
              name: { get_property: [ SELF, resource_config, cloudify_agent_name ] }
      cloudify.interfaces.lifecycle:
        create:
          implementation: tools.cloudify_deployment_proxy.tasks.wait_for_deployment_ready
          inputs:
            state:
              default: 'terminated'
            timeout:
              default: 60
        start:
          implementation: tools.cloudify_deployment_proxy.tasks.query_deployment_data
          inputs:
            daemonize:
              default: false
            interval:
              default: 1
            timeout:
              default: 15
