plugins:

  cfy_util:
    executor: central_deployment_agent
    package_name: cloudify-utilities-plugin
    source: https://github.com/cloudify-incubator/cloudify-utilities-plugin/archive/1.3.1.zip
    package_version: '1.3.1'

  cloudify_custom_workflow:
    executor: central_deployment_agent
    package_name: cloudify-utilities-plugin
    source: https://github.com/cloudify-incubator/cloudify-utilities-plugin/archive/1.3.1.zip
    package_version: '1.3.1'

  cloudinit:
    executor: central_deployment_agent
    package_name: cloudify-utilities-plugin
    source: https://github.com/cloudify-incubator/cloudify-utilities-plugin/archive/1.3.1.zip
    package_version: '1.3.1'

  configuration:
    executor: central_deployment_agent
    package_name: cloudify-utilities-plugin
    source: https://github.com/cloudify-incubator/cloudify-utilities-plugin/archive/1.3.1.zip
    package_version: '1.3.1'

  keys:
    executor: central_deployment_agent
    package_name: cloudify-utilities-plugin
    source: https://github.com/cloudify-incubator/cloudify-utilities-plugin/archive/1.3.1.zip
    package_version: '1.3.1'

  suspend:
    executor: central_deployment_agent
    package_name: cloudify-utilities-plugin
    source: https://github.com/cloudify-incubator/cloudify-utilities-plugin/archive/1.3.1.zip
    package_version: '1.3.1'

  terminal:
    executor: central_deployment_agent
    package_name: cloudify-utilities-plugin
    source: https://github.com/cloudify-incubator/cloudify-utilities-plugin/archive/1.3.1.zip
    package_version: '1.3.1'
