plugins:

  tools:
    executor: central_deployment_agent
    source: https://github.com/cloudify-incubator/cloudify-proxy-plugin/archive/v1.0.0.zip

data_types:

  cloudify.datatypes.Deployment:
    properties:
      deployment_id:
        description: >
          This is the deployment that the node is a proxy to.
        required: true
      blueprint_id:
        description: >
          This is the blueprint_id that the deployment is created from.
        required: false
      outputs:
        description: >
          A dictionary of "{ key: value, key: value }".
          Get "key" the deployment.
          Set "value" runtime property to the value of the output.
        required: false
      unvalidated:
        default: {}

node_types:

  cloudify.nodes.DeploymentProxy:
    derived_from: cloudify.nodes.Root
    properties:
      use_external_resource:
        type: boolean
        default: true
      resource_config:
        type: cloudify.datatypes.Deployment
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: tools.cloudify_deployment_proxy.tasks.wait_for_deployment_ready
          inputs:
            state:
              default: 'terminated'
            timeout:
              default: 60
        start:
          implementation: tools.cloudify_deployment_proxy.tasks.query_deployment_data
          inputs:
            daemonize:
              default: false
            interval:
              default: 1
            timeout:
              default: 15

  cloudify.nodes.DeploymentProxy.Compute:
    derived_from: cloudify.nodes.Compute
    properties:
      agent_config:
        default:
          install_method: none
      use_external_resource:
        type: boolean
        default: true
      resource_id:
        type: string
        description: The deployment ID.
        required: true
      resource_config:
        type: cloudify.datatypes.Deployment
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: tools.cloudify_deployment_proxy.tasks.wait_for_deployment_ready
          inputs:
            state:
              default: 'terminated'
            timeout:
              default: 60
        start:
          implementation: tools.cloudify_deployment_proxy.tasks.query_deployment_data
          inputs:
            daemonize:
              default: false
            interval:
              default: 1
            timeout:
              default: 15
